### ISSUE TITLE
[Request] Allow for user defined polling frequency

### ISSUE THREAD

**Issue by wmaciel** [ponewheel/android-ponewheel#1]
The app currently logs the every second.
It would be very useful to have that frequency configurable from the app UI.
Personally, I'd like to have a smaller gap between polls.
What would be the limits on how fast those requests can go through BT?

**Comment by kwatkins** [comment]
This could be configurable, they come through quickly - not sure how fast, but it's in the milliseconds. I'm about to test this on my new OneWheel+ and if there is another release I'll add this configurable feature.

**Comment by wmaciel** [comment]
Awesome,

I've made this change myself and tested it on my V1 and the logging did indeed came in the milliseconds, but for some reason they are not regular intervals.

I don't have a UI change yet, it is all hard coded.

I'll try working on it and submitting a pull request, if you won't mind.

**Comment by kwatkins** [comment]
@wmaciel Of course! and apologies i didn't get back sooner, just saw this and will work on being more active with this project... and now kicking myself for working on this when you were, i'm sure what you did is cleaner, and will definitely git pull what you have. If you get a chance check out what I did and put in the master branch, I added a new preference option for specifying polling frequency. Completely untested.

**Comment by kwatkins** [comment]
also @wmaciel based on your onewheel-video-hud you seemed to figure out the roll angle etc, i'm definitely open to making any post-processing of those values be directly in the app and output csv.

**Comment by wmaciel** [comment]
To be honest I haven't touched anything since my last comment.
I'll take a look at your changes and see if mine still apply.
I have no experience with android dev ui, so I'll do my best.

**Comment by wmaciel** [comment]
I think could probably be closed.
Thanks for the replies!
