### ISSUE TITLE
[Feature Request] Dropbox integration

### ISSUE THREAD

**Issue by wmaciel** [ponewheel/android-ponewheel#14]
It would be very handy if the app could automagically upload your newest log files to dropbox or some other cloud storage service.

As it stands now, one needs a third party app to find the log files and share them somewhere else.

**Comment by wmaciel** [comment]
I plan on work on this on my following spare time.

**Comment by ebabel** [comment]
@wmaciel This doesn't look too hard: https://www.dropbox.com/developers-v1/core/start/android
I was thinking about going DB instead of file, but conversion shouldn't be too hard. 

Are you uploading the file for adding to a video? I'd like to see that in action if you have some videos to share :)

**Comment by wmaciel** [comment]
Yes, I have a project where I am trying to create a stats overlay over my go pro footage.

I am still having some trouble with flickering on the videos, that is why I haven't published any.

Will soon.

---

i like the DB idea. Is it faster than file writing? A problem with file writing is the IO blocking and the high polling frequency make irregular intervals. Maybe DB solves that?

**Comment by ebabel** [comment]
@wmaciel had a thought, it might be easier for you to add a 'share' intent for the file instead of integrating with dropbox. Might be easier for users who don't have dropbox as well since its also a 3rd party

I think its up to you, just trying to be helpful

**Comment by wmaciel** [comment]
@ebabel Why not both?

My android dev knowledge is very limited, so I'll study on how to get those done.

**Comment by ebabel** [comment]
both is fine too if you have the time :) adding the 'share' intent is like 5 minutes of work, dropbox integration is probably at least a few hours.

DB is faster, but regardless of that we should be doing both async instead of blocking the UI

**Comment by ebabel** [comment]
I was thinking more about what you said with the file writing being slow, its because we're closing the file and flushing the buffer on every write. Although safer from loss prevention it is very bad for performance. The database would not have this issue.

**Comment by ebabel** [comment]
Sorry for the tangent but if you don't mind sending, I'd still like to see the video even if there is flickering :)

**Comment by kwatkins** [comment]
Love the action_send/sharing intent, opens up the data to any app that read it with just a few lines of code. It's mainly used for simple text, but even for sharing the OW stats files it works good enough. 

Fully agree on moving the OW stats from file to a DB content provider, would clean up the technical debt hackery I put in that you all are having to work around (sorry!). It might make it slightly tricky to use the sharing intent (since it'll be pulled from the provider) but still easily doable. 

And definitely, share the video @wmaciel ! - I'm also wondering how easy it would be to sync/overlay with video taken from the mobile device, or syncing with video uploaded to youtube.

**Comment by ebabel** [comment]
Don't be sorry Kevin, gotta start somewhere and I'm glad you did!

**Comment by ebabel** [comment]
@wmaciel we can close this, right?

**Comment by wmaciel** [comment]
i think so.
we got a way to share the file from within the app now.
I think adding auto sync with dropbox or drive could come after we have the logs in a db, otherwise we'll have to redo a lot of work.
