### ISSUE TITLE
[FR] File maintenance in app

### ISSUE THREAD

**Issue by ebabel** [ponewheel/android-ponewheel#15]
- Delete files

- see details about file in list view
  - trip length
  - nicely formatted date
  - maybe a mini-map?
  - maybe sort/filter the list?

- "share" files? formatted post to facebook/twitter?

this would all probably be more manageable if the logs were actually in DB instead of files

**Comment by kwatkins** [comment]
Yeah your onto it, throw the data in a DB content provider.

**Comment by ebabel** [comment]
@wmaciel Maintaining the order of the characteristics for csv format may be a bit tricky. Would you mind switching to a json format? Still waiting for a 🎦

**Comment by wmaciel** [comment]
@ebabel JSON would be fine, much more resilient actually. I can make the changes on my other project once it goes live.

Are we planning on switching to JSON before going into the DB format?

When you say putting the logs in the db, what exactly is being written there?
Would every log entry be an entry in the database? or every file?
Is JSON the file the db naturally outputs when?

BTW, I've uploaded my latest draft of the video. I got rid of the flickering but the logs and the video fall out of sync as the video goes along. I need to figure out a way to sync them better. Here is the unlisted youtube link for your pleasure :) https://www.youtube.com/watch?v=O2tJWJzNAFU

**Comment by ebabel** [comment]
Right now, on my branch, data is going straight into the db, as text values in relational tables. There ideally would be no files created by default and only created when the user wants to export a certain ride. 
Looking at the [branch](https://github.com/ponewheel/android-ponewheel/tree/saving-to-db/app/src/main/java/net/kwatts/powtools/database) you can see that Ride, Moment, and Attribute are all entities (tables in the db).

JSON is NOT a natural output of the db and requires a little work, the natural output is actually a .db (sqlite) file that you should be able to read from python with some 3rd party lib. If you're willing to use this instead of JSON and csv then that makes things easier. [Here](https://medium.com/@sreekumar_av/how-to-export-backup-room-db-and-view-all-the-tables-using-sqlite-viewer-9b053d44690f) is a quick guide for exporting the db. 

That's an awesome video, I could definitely see people wanting to use that! Any thoughts on adding a track/mini-map too? I was thinking about adding a mini-track to the list page.

**Comment by wmaciel** [comment]
I could work with .db, but I think that would make it harder for other people that just want to look at their logs in something like excel, or tableau.

I even think that JSON is already be adding an extra layer of complexity if anyone just wants to start looking at the data in excel, for instance. But it might be okay because it is still text file readable.

I'd rather stick to JSON or csv as exporting formats.

what do you think?

**Comment by ebabel** [comment]
I was thinking/hoping we could make the app nice enough for users to stay
in the app, but there is no reason we can't also provide the export to
Excel feature as well.
Just a little more work and hopefully the order of the columns won't be
difficult to maintain.
Maybe alphabetically or something

**Comment by ebabel** [comment]
this is done I think. but we are still saving the file in the old way in addition to the new way, need to clean that up

**Comment by ebabel** [comment]
@wmaciel can you test your video creation from the latest version of master and close this bug?
