### ISSUE TITLE
[Discussion] Kotlin

### ISSUE THREAD

**Issue by ebabel** [ponewheel/android-ponewheel#24]
How do you guys feel about adding in a little bit, or a lot of Kotlin?

Would it motivate you to contribute more or less to the project?

**Comment by wmaciel** [comment]
Personally, I am not familiar with Kotlin at all. So I'll be less inclined to contribute. Getting around the android API is a big enough hurdle for me.

If I am the minority though, I can try and take it on.

**Comment by kwatkins** [comment]
Same, not familiar with Kotlin and first I've seen of it. It may be good, although I can say in my experience languages/frameworks that take ramp-up time to learn from contributors lead to, eh, less contributions :)

**Comment by ebabel** [comment]
I feel strongly that contributors are most important, closing for now and will circle back later.

**Comment by twyatt** [comment]
I think allowing Kotlin in the codebase will encourage more contribution. As many developers are looking to improve their Kotlin skills and contributing to open source is a great way to get practice in an open forum.

That being said, Kotlin is fully interoperable with Java, so those who are more comfortable with Java can continue their contributions in Java.

**Comment by ebabel** [comment]
Ok, let's go with @twyatt's PR and see what shakes out with contributions. We should aim to keep massive overhauls off of the table so as to reduce impact. 
It's quite likely at this point that Kotlin is the future of Android and I think you guys will like it. As Travis said its easy to call kotlin code from Java, and I'm totally down to help out with that. If you want an awesome primer, check out the [koans](https://try.kotlinlang.org/#/Kotlin%20Koans/Introduction/Hello,%20world!/Task.kt).
