### ISSUE TITLE
CircleCI builds are failing

### ISSUE THREAD

**Issue by ebabel** [ponewheel/android-ponewheel#28]
Probably due to out of memory. Maybe because of all the test dependencies? We should choose which ones we need, or delete them and add as needed.

**Comment by ebabel** [comment]
@twyatt still OOM but now passing, see [92](https://circleci.com/gh/ponewheel/android-ponewheel/92)

**Comment by twyatt** [comment]
Well that's concerning: an exception is thrown during build but still "succeeds". I'll try to find some time to look into it.
