### ISSUE TITLE
Add Travis CI & automatic builds to repo 

### ISSUE THREAD

**Issue by kwatkins** [ponewheel/android-ponewheel#3]
https://medium.com/@harmittaa/travis-ci-android-example-357f6e632fc4

**Comment by ebabel** [comment]
@kwatkins you and I can get builds [here](https://circleci.com/gh/ponewheel/android-ponewheel/11#artifacts/containers/0)

Does that satisfy this ticket?

Alternatively I found [this](https://github.com/Triple-T/gradle-play-publisher#usage) which will auto sign and upload to the play store, but looks a little involved in setting up.

**Comment by kwatkins** [comment]
Yeah looks like I need to update the one on the app market soon
