### ISSUE TITLE
How I added an on-the-go battery for OW+...

### ISSUE THREAD

**Issue by kwatkins** [ponewheel/android-ponewheel#44]
Not an issue/feature request/etc more of wanted to pass the notes on my latest project to team... I finally succeeded in getting a battery pack and charger etc to be able to charge on the go. Now can finally make it to the ocean on the golden gate park runs...

![img_20171216_153225](https://user-images.githubusercontent.com/854957/34190322-db65912e-e4f4-11e7-8a75-4caaa7b0e465.jpg)

You need, 
- the solar charger controller ($38) https://www.amazon.com/gp/product/B01HCL7LEW
- liIo 36V battery ($45) http://www.ebay.com/itm/NEW-SAMSUNG-18650-36V-4-4AH-BATTERY-EBIKE-VAPE-POWERWALL-BATTERIES-20-CELLS-BMS-/201895735309?epid=1621923126&hash=item2f01ec700d:g:Mh8AAOSwSypY9Y7d
- old laptop power cable to charge the battery supporting 12-30VDC @ >5A

Then it's solder city converting everything to XT60 plugs. For charging the battery w/ the laptop power cable the solar charger is set to 42V/1.5A and for charging the OW+ from the battery solar charger is set to 58V/3.5A

If any of you are going down this rabbit hole let me know, took a bit of time to get this working with electrical smoke and bit of scare that I don't wish on anyone :)

**Comment by iSalah** [comment]
Hi Kevin,

Thanks for sharing your project.
I'm about to follow your steps and have a few questions if you don't mind:

Does your setup include any battery over discharge protection ?
Can you get a full OW+ charge with your battery ? If so, how long does it take to fully charge your OW+ ?

Thank you for your help :)

**Comment by kwatkins** [comment]
Hi iSalah -

Good question, overcharge protection is baked into the board BMS (battery
management system) - it will prevent any overcharging with the setup, just
like if you charged off AC and adapter.

I was able to get a full charge, took about 20 mins? or around there.
Definite must for OW+. Now I'm riding a OW+ XR and wow, thing goes forever,
I'm going up to 15 miles on a single charge. Also the setup to charge also
works on the XR (63V/3.2A), although tbh XR doesn't need it, thing just
goes.
