### ISSUE TITLE
Add a "donate" button under settings  

### ISSUE THREAD

**Issue by kwatkins** [ponewheel/android-ponewheel#50]
One thing that I've been asked before is how to donate, what about adding a donate option, mentioning it would go to the contributors their time (and likely to their OW funds). Is there an easy service that would do this? Even better if it actually showed contributions and total, an incentive for people to donate.

**Comment by ebabel** [comment]
https://github.com/PrivacyApps/donations

**Comment by kwatkins** [comment]
Well damn, bitcoins will get us the toys... I'll look into adding this.

**Comment by ebabel** [comment]
Just found this: https://moneybadger.io/
better than just giving out a bitcoin address?

**Comment by kwatkins** [comment]
Closing, we got a PayPal link for now.
