### ISSUE TITLE
Ride Mode Switching On-the-fly

### ISSUE THREAD

**Issue by muellergit** [ponewheel/android-ponewheel#52]
Thank you for the app improvements so far, adding the plus and also logging interval.

I was testing the beta app while indoors (it has been too cold and salty/filthy to try outside) and noticed that the ride mode can be changed while moving! This is a feature I have seen mentioned in the groups several times. How much testing has been done to see how the OW responds to switching at higher speeds? I wonder what would happen if the mode was switched from Delirium to Sequoia while riding at 13MPH. Would Sequoia slam the tail into the ground since this speed is beyond that mode's pushback speed?

**Comment by ebabel** [comment]
My guess is that the board isn't actually changing these modes but there is a bug in the app that makes it look like this is happening. @kwatkins what do you think?

@muellergit thanks much for using the app and letting us know!

**Comment by ebabel** [comment]
A safer way to test this would be to switch from one mode to another at 3-5 mph. Then close out the app and open the official app and see what mode you're in.

**Comment by kwatkins** [comment]
It actually does change the riding mode on the fly! One of the stronger differentiating features of our app IMO. I use it all the time, especially when going from concrete (mission mode) to dirt trails (delerium)

**Comment by biell** [comment]
My question, then, would be why does the official app require you to be at 1MPH or lower?  Is it b/c they aren't sure it is safe, or could potentially harm the board?  I would guess it is the former.  If it is the former, then you sill may want a max speed, like 12MPH whereby the board will clearly have enough reserve power to handle the transition.

I know that there are programs which override a phones buttons.  Would it be possible to have the volume up and volume down buttons binded to specific modes?  For people in hilly areas, I bet they would love being able to transition into elevated by pressing the volume up on their phone, then transitioning to either mission or delerium by pressing volume down when they got to the top!  The best interface would allow you to choose which modes volume up and down place you in.

**Comment by muellergit** [comment]
It definitely changes mode. I can feel the nose elevating after switching
from Mission to Elevated. I just can't test it at speed in my apartment
(weather and salt outside preventing me from getting out).

**Comment by ebabel** [comment]
Yeah, I think we should do this ASAP: prevent user from changing while at speed (unless they change it in the settings). This sounds too dangerous to be allowed by default.
Regarding the volume buttons: absolutely do-able. If thats really what you want. Seems like it could be less than desirable with the ease in which you could switch to beginner mode and get kicked off. I like @biell's idea: a max speed per mode. Maybe even voice-to-text confirmation of the new mode?

Also, @biell, it could be that the official app doesn't want you're attention off the road.

**Comment by kwatkins** [comment]
Agree on the speed check before ride mode change, I'll pick that one up. I'm fairly sure the speed change would be gradual but without knowing for sure best be safe. I might just try it, on grass or some soft spot landing :)

Almost certain the official app is doing it for safety reasons. 

The volume change, I do like this. Some where you have the volume up/down in settings w/ a dropdown set to the mode to set. It's easy to override the keycode of volume up/down in Android. It could get annoying for those that use the volume when riding to listen to audio (like me) but as a setting it sounds legit. Will plan to roll this issue into a feature...

**Comment by muellergit** [comment]
Changing modes on the fly is a great feature if it is safe! Not sure about
using the volume up down buttons because Elevated is in between Mission and
Delirium and I would not want to move through Elevated if I wanted to go
back and forth between Mission and Delirium (and for the reason of
adjusting the volume of my music also).

**Comment by kwatkins** [comment]
This has been done, also found out that the board prevents the riding mode change when your going 12+mph, so it's got our back :)
