### ISSUE TITLE
Identify + fix BLE re-connection issue

### ISSUE THREAD

**Issue by kwatkins** [ponewheel/android-ponewheel#63]
Whenever there is a disconnect to OW device that isn't done by the user - for example, turning off the OW without hitting the "disconnect" button, the app has problems trying to reconnect. The workaround could be either fully closing and restarting the app and/or turning on and off bluetooth in the device settings. 

I'm not sure what is going on, logs aren't showing much, so adding verbose logs in the BluetoothImpl may shed light. If there is a solid open sourced + maintained library that deals with the Android BLE buggy af stack I'm all about moving to it...

**Comment by ebabel** [comment]
I have a friend working on one and has investigated all of them he can find. He says there is sadly no silver bullet.

**Comment by kwatkins** [comment]
Sad panda.

**Comment by twyatt** [comment]
As @ebabel mention, It isn't easy to get bluetooth right on Android, but this might help...

In your `BluetoothUtilImpl`:

https://github.com/ponewheel/android-ponewheel/blob/bbc9cd217252aeb8ef5b313ce923b3934c64b180/app/src/main/java/net/kwatts/powtools/util/BluetoothUtilImpl.java#L328-L345

Upon disconnect you reconnect using `BluetoothDevice.connectGatt`:

https://github.com/ponewheel/android-ponewheel/blob/bbc9cd217252aeb8ef5b313ce923b3934c64b180/app/src/main/java/net/kwatts/powtools/util/BluetoothUtilImpl.java#L315-L318

When using [`BluetoothDevice.connectGatt`] you should clean up the previous connection using [`BluetoothGatt.close`], **or** use [`BluetoothGatt.connect`] to reconnect.

[`BluetoothDevice.connectGatt`]: https://developer.android.com/reference/android/bluetooth/BluetoothDevice.html#connectGatt(android.content.Context,%20boolean,%20android.bluetooth.BluetoothGattCallback)
[`BluetoothGatt.close`]: https://developer.android.com/reference/android/bluetooth/BluetoothGatt.html#close()
[`BluetoothGatt.connect`]: https://developer.android.com/reference/android/bluetooth/BluetoothGatt.html#connect()

**Comment by kwatkins** [comment]
Thanks Travis, I'll give this a try!

**Comment by kwatkins** [comment]
@Travis that did the trick. Now onto the next bug after fixing that one,
the board reconnects but the UI thread doesn't. That should be easy
compared to this one, big thanks again for spotting it.

**Comment by kwatkins** [comment]
This is fixed, thanks again. This actually made the last release the most solid yet,
