### ISSUE TITLE
Support multiview

### ISSUE THREAD

**Issue by kwatkins** [ponewheel/android-ponewheel#64]
Looks like when jumping into multiview the UI resets and disconnects, not sure what is needed but it would be cool to have this support.

**Comment by ebabel** [comment]
Texting while riding? Or maybe filming?

I have a feeling all we need to do is capture configChanges, not too difficult.

**Comment by audkar** [comment]
I believe multiview is working now. Moving Bt connection to separate service solved this. @kwatkins

**Comment by kwatkins** [comment]
@audkar awesome! I'll test it out. Also increased your access to the repo, you should see the invite.

**Comment by kwatkins** [comment]
Tested, works fine with master branch. Nicely done @audkar
