### ISSUE TITLE
Android 4.4 support?

### ISSUE THREAD

**Issue by ocornu** [ponewheel/android-ponewheel#67]
I'm looking into cheap wrist Android phones, like the [DM98](https://www.aliexpress.com/item/Smartch-Original-DM98-Smart-Watch-MTK6572-3G-Smartwatch-900mAh-Battery-512MB-Ram-4GB-Rom-Camera-Bluetooth/32835711258.html?spm=a2g0s.13010208.99999999.269.mfRIVt)  or LEM4, but most come only with Android 4.4.
What's requiring Android 5.0+ in POnewheel?

**Comment by ebabel** [comment]
I bet you could spend a fair amount of time optimizing it for the cheaper phones with lower battery capacity and slower CPU. Neat idea though!

**Comment by ocornu** [comment]
Thanks kwatkins! I don't have the phone yet though: was investigating before i pull the trigger...
Are you suggesting I another option, ebabel?

I've developed in many languages, Java included, but I've never worked with Android. Should I expect a lot of difficulty? How long to get from zero to successfully compiling an APK you guys think?

**Comment by ebabel** [comment]
Yeah for sure, the difficulty isn't in making your first app, its more about supporting old phones with BLE, or optimizing performance/battery drain. To be honest, its hard to say how our app would do on those phones, but I like @kwatkins's optimism!

**Comment by audkar** [comment]
Android 4.4 doesn't support BLE at all. [Doc link](https://developer.android.com/reference/android/bluetooth/BluetoothAdapter.html#getBluetoothLeScanner()) This is mandatory method for application and it was added from android 5.0 (sdk 21)
https://github.com/ponewheel/android-ponewheel/blob/0799bf50e5174cc2c3afbe47daee120c4c14393e/app/src/main/java/net/kwatts/powtools/util/BluetoothUtilImpl.java#L427-L432
think current code which exists in `master` branch will crash at run-time on android 4.4. Need to test this before release. And revert minSdk 19->21 if it is true.

**Comment by audkar** [comment]
@kwatkins @ebabel What do you think?

**Comment by kwatkins** [comment]
Sounds good to me.

**Comment by ebabel** [comment]
Thanks for looking into that @audkar. I'm all for sticking with 21
