### ISSUE TITLE
pOnewheel v 3.3 Fatal exception after setting Logging Frequency in android 7.0

### ISSUE THREAD

**Issue by ammarraisafti** [ponewheel/android-ponewheel#70]
The application stops when setting the log frequency.

**Comment by kwatkins** [comment]
Cool, thanks for logging. Should be an easy fix.

**Comment by ammarraisafti** [comment]
okay, thanks again.
I want to ask. Would you like to receive a new Logo contribution for this
project. If you want to accept it. I'll be designing a sweet new logo for
this app. And give me some time to work on it for a few days. thank you

Pada tanggal Sen, 18 Jun 2018 01:37, Kevin Watkins <notifications@github.com>
menulis:

**Comment by kwatkins** [comment]
Ahh thanks for the offer, current logo is fine.
