### ISSUE TITLE
Current targetSdkVersion 21 doesn't met mandatory requirements

### ISSUE THREAD

**Issue by audkar** [ponewheel/android-ponewheel#72]
Since 2018 November it is required that all applications target at least Android SDK version 26. [Docs](https://developer.android.com/distribute/best-practices/develop/target-sdk)

I have looked to source code very briefly and see some changes which will be required to increase version:
- [ ] Runtime permissions
  - Location
  - External storage
- [ ] Doze mode, foreground services. Probably clean solution would be to refactor `Wake lock` to foreground service

Do you know any additional features which app uses and needs to update while migrating to target version 26?

Are you willing to accept contributions (PRs) to solve this issue?

**Comment by ebabel** [comment]
regarding accepting contributions: Absolutely!
