### ISSUE TITLE
New Logo/Icon proposal

### ISSUE THREAD

**Issue by mansya** [ponewheel/android-ponewheel#85]
Good day sir. I am a graphic designer and i am interested in designing a logo for your good project. I will be doing it as a gift for free. I just need your permission first before I begin my design. Hoping for your positive feedback. Thanks

**Comment by mansya** [comment]
hi sir. how about this offer? are you interested ?

**Comment by SampsonCrowley** [comment]
@mansya if you're doing it for free, just do it and they can either accept or reject your submission.

I'm not sure what "permission" you need from them, but even if you get "permission", that's still not a guarantee your logo will be used if they don't like the end result

**Comment by SampsonCrowley** [comment]
@mansya this is all open source. you can either put in some work and contribute, or not. there's no guarantee your work will be used
